version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: f31ab31e-f28c-420e-80dd-f60679f204c9
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
