version: 1.0
app:
  instances: 
    min: 1
    max: 1
  version: 0671904e-66b2-4186-a597-d2379b7e6283
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=prod"
    - name: MAX
      value: "5"
